version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tutor
    ports:
      - "3306:3306"
    volumes:
      - my-db-volume:/var/lib/mysql

volumes:
  my-db-volume:
