import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ToastProvider } from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-provider'
import ThemeProvider from '@/components/providers/ThemeProvider'
import ClientProvider from '@/components/providers/ClientProvider'

import "@stream-io/video-react-sdk/dist/css/styles.css"; 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider>

            <ConfettiProvider />
            <ToastProvider />
            <ClientProvider>
              {children}
            </ClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
